### ISSUE TITLE
Syntax highlight for wrongly indented terms

### ISSUE THREAD

**Issue by inutano** [manabuishii/vscode-cwl#2]
@tonyyzy and I found that the vscode-cwl highlights the `outputs` keyword even when it is placed at the wrongly indented position. 

The `outputs` keyword in the CWL file like below should not be highlighted because it's at the wrong position:

```
inputs:
  hoge:
    type: string
    inputBinding:
      prefix: --hoge
  outputs:
    hoge_out:
      type: File
      outputBinding: *
```
